version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.5

    working_directory: /go/src/github.com/larrylv/cryptopals
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
